[DV-6720] Upgraded client to PHP ^8.2 and updated related symfony packages/contracts
superbrave/auth0-http-client pull request #14
Opened 2023-12-14 08:42 UTC by beau-ottens

| Q | A
| - | -
| ⏱ Review tijd | 5 min
| ⌨️ Type wijziging | ➕ Nieuwe feature
| ⬆️  Version increase | Major

### ✍️ Wijzigingen
Upgrade naar Symfony 6.4

### 🪜 Stappen om te testen
- Laadt package in applicatie (dmv `composer require superbrave/auth0-http-client:dev-DV-6720-post-eventsauce-upgrade`)
- Voer een request uit waarbij authenticatie benodigd is
- Zie dat er een token op de achtergrond wordt opgevraagd en dat deze gecached wordt

### ✅ Checklist
- [x] Acceptatie criteria story gecheckt

2023-12-14 08:55 UTC, hansgoed requested changes

2023-12-15 11:40 UTC, kkevindev approved these changes

2023-12-15 11:40 UTC, kkevindev commented on src/AuthZeroAuthenticatingHttpClient.php
> +        private HttpClientInterface $client,
mag readonly

2023-12-15 11:40 UTC, kkevindev commented on src/AuthZeroAuthenticatingHttpClient.php
> +        private ArrayAdapter|CacheInterface|null $accessTokenCache = null,
`ArrayAdapter` is een implementatie van `CacheInterface`. Willen we dan niet gewoon `?CacheInterface` of `?ArrayAdapter` als parameter hebben?

2023-12-15 11:40 UTC, kkevindev commented on src/AuthZeroAuthenticatingHttpClient.php
> -    public function stream($responses, float $timeout = null): ResponseStreamInterface
Gebruiken we deze NERGENS?

2024-01-03 12:07 UTC, jvdhehvg approved these changes

2024-01-03 12:31 UTC, atehvg commented on src/AuthZeroAuthenticatingHttpClient.php
> -    public function stream($responses, float $timeout = null): ResponseStreamInterface
De decorator trait heeft deze implementatie al

2024-01-03 12:31 UTC, atehvg approved these changes

2024-01-03 13:15 UTC, atehvg commented on src/AuthZeroAuthenticatingHttpClient.php
> +        private HttpClientInterface $client,
De client zet ik nu in een losse property, omdat de trait het vereist.

2024-01-03 13:15 UTC, atehvg commented on composer.json
> +        "php": "^8.2",
Yes and we support it from 8.2

2024-01-03 14:17 UTC, jvdhehvg approved these changes

2024-01-03 14:17 UTC, merged